server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-management
    username: root
    password: test1234!
  application:
    name: ProductManagement
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true