services:
  product-management-mysql:
    image: mysql
    restart: always
    container_name: "product-management-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'test1234!'
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - product-management-mysql-data:/var/lib/mysql

  product-management-redis:
    image: "redis:latest"
    container_name: "product-management-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - product-management-redis-data:/data

volumes:
  product-management-redis-data:
  product-management-mysql-data: