services:
  product_management-mysql:
    image: mysql
    restart: always
    container_name: "product_management-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'pass1234!'
      MYSQL_DATABASE: 'product_management'  # Add this line
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - product_management-mysql-data:/var/lib/mysql

  product-management-redis:
    image: "redis:latest"
    container_name: "product-management-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - product-management-redis-data:/data

volumes:
  product-management-redis-data:
  product_management-mysql-data: